name = "Grom Restricted Arsenals"
prefix = "GRRA"

[version]
path = "addons/grra/script_version.hpp"
major = 1
minor = 0
patch = 4
build = 3
git_hash = 8

[lints.sqf]
command_case = "Error" # enforce command case
