name: Build & Release

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Setup HEMTT
              uses: arma-actions/hemtt@v1           
            - name: Run HEMTT build
              run: hemtt release
            - name: Upload Release
              uses: actions/upload-artifact@v4
              with:
                  name: grra-release
                  path: release/grra.zip